# Generated by Django 3.1.3 on 2021-02-21 08:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('PK_Cart', models.AutoField(db_column='PK_Cart', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'Cart',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('PK_Category', models.AutoField(db_column='PK_Category', primary_key=True, serialize=False)),
                ('categoryName', models.CharField(db_column='categoryName', max_length=100)),
            ],
            options={
                'db_table': 'Category',
            },
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('PK_Color', models.AutoField(db_column='PK_Color', primary_key=True, serialize=False)),
                ('colorName', models.CharField(db_column='colorName', max_length=100)),
            ],
            options={
                'db_table': 'Color',
            },
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('PK_Size', models.AutoField(db_column='PK_Size', primary_key=True, serialize=False)),
                ('sizeName', models.CharField(db_column='sizeName', max_length=100)),
            ],
            options={
                'db_table': 'Size',
            },
        ),
        migrations.CreateModel(
            name='ClothesOrder',
            fields=[
                ('PK_ClothesOrder', models.AutoField(db_column='PK_ClothesOrder', primary_key=True, serialize=False)),
                ('nameClient', models.CharField(db_column='nameClient', max_length=255)),
                ('phoneClient', models.CharField(db_column='phoneClient', max_length=100)),
                ('emailClient', models.EmailField(db_column='emailClient', max_length=254)),
                ('cart', models.ForeignKey(blank=True, db_column='PK_Cart', null=True, on_delete=django.db.models.deletion.CASCADE, to='ClothingStoreApp.cart')),
            ],
            options={
                'db_table': 'ClothesOrder',
            },
        ),
        migrations.CreateModel(
            name='Clothes',
            fields=[
                ('PK_Clothes', models.AutoField(db_column='PK_Clothes', primary_key=True, serialize=False)),
                ('clothesName', models.CharField(db_column='clothesName', max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('imagePath', models.ImageField(blank=True, db_column='imagePath', max_length=255, null=True, upload_to='')),
                ('description', models.TextField(blank=True, null=True)),
                ('PK_Category', models.ForeignKey(db_column='PK_Category', on_delete=django.db.models.deletion.DO_NOTHING, to='ClothingStoreApp.category')),
                ('PK_Color', models.ForeignKey(db_column='PK_Color', on_delete=django.db.models.deletion.DO_NOTHING, to='ClothingStoreApp.color')),
                ('PK_Size', models.ForeignKey(db_column='PK_Size', on_delete=django.db.models.deletion.DO_NOTHING, to='ClothingStoreApp.size')),
            ],
            options={
                'db_table': 'Clothes',
            },
        ),
        migrations.AddField(
            model_name='cart',
            name='items',
            field=models.ManyToManyField(to='ClothingStoreApp.Clothes'),
        ),
    ]
