# Generated by Django 3.1.3 on 2021-02-21 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClothingStoreApp', '0002_auto_20210221_1506'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='totalItems',
            field=models.PositiveIntegerField(db_column='totalItems', default=0),
        ),
        migrations.AddField(
            model_name='cart',
            name='totalPrice',
            field=models.DecimalField(db_column='totalPrice', decimal_places=2, default=0, max_digits=15),
        ),
    ]
