# Generated by Django 3.1.3 on 2021-02-21 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ClothingStoreApp', '0003_auto_20210221_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='totalItems',
            field=models.PositiveIntegerField(db_column='totalItems'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='totalPrice',
            field=models.DecimalField(db_column='totalPrice', decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name='clothesorder',
            name='cart',
            field=models.ForeignKey(blank=True, db_column='PK_Cart', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ClothingStoreApp.cart'),
        ),
    ]
